name: stats-studies
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas 
  - jupyterlab
  - boost-histogram
  - scipy
  - matplotlib
  - numba-stats
  - pyhf
  - hepstats
  - root
  - zfit
  - numba-scipy
  - jupyter-book
  - iminuit
  - ghp-import
  - ipympl